name: _android-build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GHA_TOKEN }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env

          workflow="self-sdk-examples:android-build"
          id=$(date | md5sum | head -c 8)
          gh workflow run ${workflow} -R joinself/github-workflows-dispatch -r main -f id=${id} -f git-ref=${CI_REF_NAME}

          echo "Calling remote workflow: ${workflow} (${id})"
          for ((i = 0; i < 60; i++)); do
            echo "Waiting for workflow to complete..."
            status=$(gh run list -R joinself/github-workflows-dispatch --json name,databaseId,conclusion --jq ".[] | select(.name==\"${workflow} - ${id}\") | (.databaseId|tostring) + \":\" + .conclusion")
            dispatch_run_id="${status%:*}"
            conclusion="${status#*:}"
            [[ "${conclusion}" == "success" ]] && echo "Workflow complete" && break
            [[ "${conclusion}" == "failure" ]] && echo "Workflow failed" && exit 1
            [[ "${i}" == "59" ]] && echo "Workflow timeout" && exit 1
            sleep 10
          done

          echo "${dispatch_run_id}" > ${CI_WORKDIR}/.ci/dispatch-run-id
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: .ci/dispatch-run-id
