name: _android-build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joinself/android-build:latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          cd android/SelfDemo
          ./gradlew :app:assembleDebug
          echo "run_id: ${{ github.run_id }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: android/SelfDemo/app/build/outputs/apk/debug/self-demo-debug.apk
