name: CI - Android

on:
  push:
    branches:
      - main
    paths:
      - 'android/SelfDemo/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/android-build.yml
    secrets: inherit
  publish:
    #if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/android-publish.yml
    secrets: inherit
    needs: build
