name: CI - Docker

on:
  push:
    branches:
      - main
    pull_request:
      - main
    paths:
      - 'java/**'
      - 'golang/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit
    needs: build
