name: CI - Docker Go

on:
  push:
    branches:
      - main
    paths:
      - 'golang/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/docker-go-*'
      - 'golang/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: joinself/actions-public/setup-job@main
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: golang
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/joinself/self-sdk-demo:go
