name: CI - Docker Go

on:
  push:
    branches:
      - main
    paths:
      - 'golang/**'
  pull_request:
    branches:
      - main
    paths:
      - 'golang/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-go-build.yml
    secrets: inherit
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/docker-go-publish.yml
    secrets: inherit
    needs: build
