name: _docker-publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Publish
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          cd ${CI_WORKDIR}/golang
          docker build -t ghcr.io/joinself/self-sdk-demo:go .

          cd ${CI_WORKDIR}/java
          docker build -t ghcr.io/joinself/self-sdk-demo:java .

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/joinself/self-sdk-demo:go
          docker push ghcr.io/joinself/self-sdk-demo:java
