name: _docker-go-publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Publish
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          cd ${CI_WORKDIR}/golang
          docker build -t ghcr.io/joinself/self-sdk-demo:go .

          echo "${GH_TOKEN}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          docker push ghcr.io/joinself/self-sdk-demo:go
