name: _go-build-linux

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25.7-trixie
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env

          mkdir -m 0755 -p /etc/apt/keyrings
          curl -fsSL https://europe-apt.pkg.dev/doc/repo-signing-key.gpg | gpg --dearmor -o /etc/apt/keyrings/self.gpg
          echo "deb [signed-by=/etc/apt/keyrings/self.gpg] https://europe-apt.pkg.dev/projects/principal-oxide-204416 apt main" > /etc/apt/sources.list.d/self.list
          apt-get update
          apt-get install -y self-sdk=0.85.0-48

          cd golang
          go build -o self-sdk-demo

          tar -czf self-sdk-demo_go_linux_amd64.tar.gz self-sdk-demo
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-artifacts
          path: golang/self-sdk-demo_go_linux_amd64.tar.gz
