name: _go-build-linux

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joinself/go-build:latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          cd golang
          go build -o self-sdk-demo
          tar -czf self-sdk-demo_go_linux_amd64.tar.gz self-sdk-demo
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-artifacts
          path: golang/self-sdk-demo_go_linux_amd64.tar.gz
