name: _go-build-mac

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Build
        shell: bash
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          brew
          homebrew
          cd golang
          GOOS=darwin GOARCH=amd64 go build -o self-sdk-demo
          tar -czf self-sdk-demo_go_darwin_amd64.tar.gz self-sdk-demo
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-mac-artifacts
          path: |
            golang/self-sdk-demo_go_darwin_amd64.tar.gz
