name: _go-publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Publish
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env

          sha256sum self-demo_go_linux_amd64.tar.gz | awk '{print $1}' > self-demo_go_linux_amd64.tar.gz.sha256

          gh release upload "latest" *.tar.gz *.sha256 --clobber
          #gh release delete "go-latest" -y --cleanup-tag || true
          #gh release create "go-latest" --latest=false --notes "" *.tar.gz *.sha256
