name: _java-publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: joinself/github-actions-public/setup-job@main
      - name: Download build artifacts
        uses: actions/download-artifact@v4
      - name: Publish
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . ${GITHUB_WORKSPACE}/.ci/env
          cd build-artifacts
          sha256sum self-sdk-demo_java.tar.gz | awk '{print $1}' > self-sdk-demo_java.tar.gz.sha256
          gh release upload "latest" *.tar.gz *.sha256 --clobber
