name: Publish - Self Demo (Docker)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        shell: bash
        run: |
          cd java
          docker build -t ghcr.io/joinself/self-demo:latest .
          docker push ghcr.io/joinself/self-demo:latest
